<?php

namespace ContainerW2EYxPc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIshikiControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\IshikiController' shared autowired service.
     *
     * @return \App\Controller\IshikiController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\IshikiController'] = $instance = new \App\Controller\IshikiController();

        $instance->setContainer(($container->privates['.service_locator.CshazM0'] ?? $container->load('get_ServiceLocator_CshazM0Service'))->withContext('App\\Controller\\IshikiController', $container));

        return $instance;
    }
}
