<?php

namespace ContainerW2EYxPc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPurchaseOrderRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\PurchaseOrderRepository' shared autowired service.
     *
     * @return \App\Repository\PurchaseOrderRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\PurchaseOrderRepository'] = new \App\Repository\PurchaseOrderRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
