<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container73Z9vtQ\App_KernelDevaDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container73Z9vtQ/App_KernelDevaDebugContainer.php') {
    touch(__DIR__.'/Container73Z9vtQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevaDebugContainer::class, false)) {
    \class_alias(\Container73Z9vtQ\App_KernelDevaDebugContainer::class, App_KernelDevaDebugContainer::class, false);
}

return new \Container73Z9vtQ\App_KernelDevaDebugContainer([
    'container.build_hash' => '73Z9vtQ',
    'container.build_id' => 'bb8f3129',
    'container.build_time' => 1689163024,
], __DIR__.\DIRECTORY_SEPARATOR.'Container73Z9vtQ');
