<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPcMXJqb\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPcMXJqb/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerPcMXJqb.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerPcMXJqb\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerPcMXJqb\App_KernelTestDebugContainer([
    'container.build_hash' => 'PcMXJqb',
    'container.build_id' => '1a4cb640',
    'container.build_time' => 1689328805,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPcMXJqb');
