<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJM7GJnA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJM7GJnA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJM7GJnA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJM7GJnA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJM7GJnA\App_KernelDevDebugContainer([
    'container.build_hash' => 'JM7GJnA',
    'container.build_id' => '4cbaa7ad',
    'container.build_time' => 1689330321,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJM7GJnA');
